export const SPENDING_CATEGORIES_FETCHED = "CATEGORIES/SPENDING_CATEGORIES_FETCHED";
export const SPENDING_CATEGORY_SELECTED = "CATEGORIES/SPENDING_CATEGORY_SELECTED";
export const SPENDING_CATEGORY_NAME_CHANGED = "CATEGORIES/SPENDING_CATEGORY_NAME_CHANGED";
export const SPENDING_CATEGORY_NOTES_CHANGED = "CATEGORIES/SPENDING_CATEGORY_NOTES_CHANGED";