export const PAYMENTS_STATE_RESET = "PAYMENTS/PAYMENTS_STATE_RESET";

//ADD PAYMENTS
export const ASSOCIATIONS_MODAL_OPENED = "ADD_PAYMENTS/ASSOCIATIONS_MODAL_OPENED";
export const ASSOCIATIONS_MODAL_CLOSED = "ADD_PAYMENTS/ASSOCIATIONS_MODAL_CLOSED";
export const INPUT_PAYMENT_ROW_ADDED = "ADD_PAYMENTS/INPUT_PAYMENT_ROW_ADDED";
export const INPUT_PAYMENT_ROW_DELETED = "ADD_PAYMENTS/INPUT_PAYMENT_ROW_DELETED";
export const INPUT_PAYMENT_ROW_CLONED = "ADD_PAYMENTS/INPUT_PAYMENT_ROW_CLONED";
export const INPUT_PAYMENT_CHANGED = "ADD_PAYMENTS/INPUT_PAYMENT_CHANGED";
export const INPUT_PAYMENT_SUBMITTED = "ADD_PAYMENTS/INPUT_PAYMENT_SUBMITTED";
export const ADD_PAYMENTS_RESET = "ADD_PAYMENTS/RESET";

//REPORTS
export const FETCH_PAYMENTS_BY_FILTERS_STARTED = "REPORTS/FETCH_PAYMENTS_BY_FILTERS_STARTED";
export const PAYMENTS_BY_FILTERS_FETCHED = "REPORTS/PAYMENTS_BY_FILTERS_FETCHED";
export const DIFF_REPORT_FETCHED = "REPORTS/DIFF_REPORT_FETCHED";
export const AGGREGATE_REPORT_FETCHED = "REPORTS/AGGREGATE_REPORT_FETCHED";
//export const PAYMENTS_PAID = "REPORTS/PAYMENTS_PAID";
