//COMMON
export const USERS_STATE_RESET = "USERS/COMMON/USERS_STATE_RESET";

//CREATE USER PAGE
export const USERNAME_CHANGED = "USERS/CREATE_USER/USERNAME_CHANGED";
export const ADD_GROUP_WITH_SINGLE_USER_CHANGED = "USERS/CREATE_USER/ADD_GROUP_WITH_SINGLE_USER_CHANGED";
export const CREATE_USER_SUBMITTED = "USERS/CREATE_USER/CREATE_USER_SUBMITTED";
export const CREATE_USER_FORM_RESET = "USERS/CREATE_USER/CREATE_USER_FORM_RESET";

//CREATE GROUP PAGE
export const USER_LIST_FETCHED = "USERS/CREATE_GROUP/USER_LIST_FETCHED";
export const GROUP_NAME_CHANGED = "USERS/CREATE_GROUP/GROUP_NAME_CHANGED";
export const GROUP_NOTES_CHANGED = "USERS/CREATE_GROUP/GROUP_NOTES_CHANGED";

//ASSOCIATE PAGE
export const GROUP_LIST_FETCHED = "USERS/CREATE_ASSOCIATIONS/GROUP_LIST_FETCHED";
export const GROUP_SELECTED = "USERS/CREATE_ASSOCIATIONS/GROUP_SELECTED";
export const ASSOCIATION_BY_GROUP_FETCHED = "USERS/CREATE_ASSOCIATIONS/ASSOCIATION_BY_GROUP_FETCHED";
export const USER_SELECTED = "USERS/CREATE_ASSOCIATIONS/USER_SELECTED";
export const RESET_ASSOCIATIONS = "USERS/CREATE_ASSOCIATIONS/RESET_ASSOCIATIONS";

