//CREATE USER PAGE
export const USERNAME_CHANGED = "USERS/CREATE_USER/USERNAME_CHANGED";
export const ADD_GROUP_WITH_SINGLE_USER_CHANGED = "USERS/CREATE_USER/ADD_GROUP_WITH_SINGLE_USER_CHANGED";
export const CREATE_USER_SUBMITTED = "USERS/CREATE_USER/CREATE_USER_SUBMITTED";
export const CREATE_USER_FORM_RESET = "USERS/CREATE_USER/CREATE_USER_FORM_RESET";

//CREATE GROUP PAGE
export const USER_LIST_FETCHED = "USERS/CREATE_GROUP/USER_LIST_FETCHED";
