//CREATE USER PAGE
export const USERNAME_CHANGED = "USERS/CREATE/USERNAME_CHANGED";
export const ADD_GROUP_WITH_SINGLE_USER_CHANGED = "USERS/CREATE/ADD_GROUP_WITH_SINGLE_USER_CHANGED";
export const CREATE_USER_SUBMITTED = "USERS/CREATE/CREATE_USER_SUBMITTED";
export const CREATE_USER_FORM_RESET = "USERS/CREATE/CREATE_USER_FORM_RESET";

