server:
  port : ${PORT:8080} #default: 8080


spring:
  jpa:
    hibernate:
      ddl-auto: UPDATE
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL8Dialect'
  datasource:
    url: jdbc:mysql://${DB_MY_SQL_HOSTNAME}:${DB_MY_SQL_PORT}/${DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: root
    driver-class-name=com: com.mysql.cj.jdbc.Driver


custom:
  exceptions:
    returnStackTrace: true
  dynamic-resources:
    path: 'C:\Users\DASAROF\Documents\Cose spam non lavoro\Documentazione spese-casa\Dynamic Resources'

DB_MY_SQL_HOSTNAME: localhost
DB_MY_SQL_PORT: 3306
DB_NAME: spese_casa