export const ALERT_SHOWN = "FEEDBACK/ALERT_SHOWN";
export const ALERT_HIDDEN = "FEEDBACK/ALERT_HIDDEN";
export const ALERT_TYPE_SET = "FEEDBACK/ALERT_TYPE_SET";
export const ALERT_SHOW_TIME_CHANGED = "FEEDBACK/ALERT_SHOW_TIME_CHANGED";
export const ALERT_STATE_RESET = "FEEDBACK/ALERT_STATE_RESET";

export const FEEDBACK_MODAL_OPENED = "FEEDBACK/FEEDBACK_MODAL_OPENED";
export const FEEDBACK_MODAL_CLOSED = "FEEDBACK/FEEDBACK_MODAL_CLOSED";
export const FEEDBACK_MODAL_TITLEKEY_SET = "FEEDBACK/FEEDBACK_MODAL_TITLEKEY_SET";
export const FEEDBACK_MODAL_SUBTITLEKEY_SET = "FEEDBACK/FEEDBACK_MODAL_SUBTITLEKEY_SET";
export const FEEDBACK_MODAL_SUCCESS_SET = "FEEDBACK/FEEDBACK_MODAL_SUCCESS_SET";
export const FEEDBACK_MODAL_STATE_RESET = "FEEDBACK/FEEDBACK_MODAL_STATE_RESET";

